blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog_app.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('post/<id>', views.single_post, name='single_post'),
    path('add_comment/<id>', views.add_comment, name='add_comment'),
    path('author/<id>', views.author_post, name='author_post'),
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout_user'),
    path('contact/', views.contact, name='contact'),
]

blog_app/models.py
from django.db import models
from tinymce import models as tinymce_models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    body = tinymce_models.HTMLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    body = models.TextField(null=False)

    def __str__(self):
        return self.body

blog_app/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import Comment, Post, Category
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import time
from . import tasks

# Create your views here.

#@login_required(login_url='/login/')
def index(request):
    data = Post.objects.order_by('-id')
    tasks.bekar.delay(5)
    return render(request, 'blog_app/home.html', {"posts" : data})

def contact(request):
    if request.method == "POST":
        msg = request.POST.get('message')
        name = request.POST.get('name')
        email = request.POST.get('email')
        tasks.mail.delay(msg, name, email)
        a = "Successfully sent message"
        render(request, 'blog_app/contact.html', {"msg" : a})

    return render(request, 'blog_app/contact.html')

def single_post(request, id):
    data = Post.objects.get(id=id)
    comments =  Comment.objects.filter(post= data).select_related('author')
    return render(request, 'blog_app/single_post.html', {"post" : data , "comments": comments})


def search(request):
    query = request.GET['q']
    data = Post.objects.filter(title__icontains=query)
    return render(request, 'blog_app/search.html', {"posts" : data})


def add_comment(request, id):
    comment_body = request.POST.get('msg')
    comment_obj = Comment(post= Post.objects.get(id=id) , author=request.user , body = comment_body)
    comment_obj.save()
    return HttpResponseRedirect( reverse('blog_app:single_post', args=(id)) )


def author_post(request, id):
    data = Post.objects.filter(author = User.objects.get(id=id)).order_by('-id')
    return render(request, 'blog_app/home.html', {"posts" : data})


def login_user(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect( reverse('blog_app:index') )
    
    if request.method == 'GET':
        return render(request, 'blog_app/login.html')
    elif request.method == 'POST':
        username =  request.POST["username"]
        password =  request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect( reverse('blog_app:index') )
        else:
            msg = "Invalid Credential"
            return render(request, 'blog_app/login.html', {"msg" : msg})

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect( reverse('blog_app:index') )
    
    if request.method == "GET":
        return render(request, 'blog_app/register.html')
    elif request.method=="POST":
        username =  request.POST["username"]
        email =  request.POST["email"]
        password =  request.POST["password"]

        if len(User.objects.filter(username=username)) != 0:
            msg = "Username Already Exists. Please use a different username."
            return render(request, 'blog_app/register.html', {"msg" : msg})

        user = User.objects.create_user(username,email, password)
        user.save()
        login(request, user)
        return HttpResponseRedirect( reverse('blog_app:index') )


def logout_user(request):
    logout(request)
    return HttpResponseRedirect( reverse('blog_app:index') )

blog_app/templates/blog_app/blog_card.html
<div class="col">
    <div class="card shadow-sm">
    <img src="{{post.thumbnail.url}}" height="250">
    <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{post.body|safe|truncatechars:100 }} </p>
        <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a class="btn-outline-secondary text-decoration-none" href="{% url 'blog_app:single_post' post.id %}">View</a></button>
            {% if user.is_authenticated %}
            <button type="button" class="btn btn-sm btn-outline-secondary"><a class="btn-outline-secondary text-decoration-none" href="/admin/blog_app/post/{{post.id}}/change/">Edit</a></button>
            {% endif %}
            
        </div>
        
        </div>
    </div>
    </div>
</div>

blog_app/templates/blog_app/blog_structure.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Django Blog</title>
    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    {% block custom_head_block %}{% endblock custom_head_block %}
    
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
  </head>
  <body>
{% include 'blog_app/navbar.html' %}
<main>

{% block header_block %}{% endblock header_block %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% block blog_card_block %}{% endblock blog_card_block %}
      </div>
      {% block single_post_block %}{% endblock single_post_block %}
      {% block single_post_comments %}{% endblock single_post_comments %}
    </div>
  </div>
</main>
{% include 'blog_app/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

blog_app/templates/blog_app/contact.html
{% extends 'blog_app/blog_structure.html' %}

{% block blog_card_block %}
   <!--Section: Contact v.2-->
<div class="container">
	<div class="row justify-content-center">
		<div class="col-12 col-md-12 col-lg-12 pb-5">
                    <!--Form with header-->
                    <form method="post">
                    {% csrf_token %}
                        <div class="card border-primary rounded-0">
                            <div class="card-header p-0">
                                <div class="bg-info text-white text-center py-2">
                                    <h3><i class="fa fa-envelope"></i> Contact Us</h3>
                                    <p class="m-0">Fill the form below</p>
                                    <p>{{msg}}</p>
                                </div>
                            </div>
                            <div class="card-body p-3">

                                <!--Body-->
                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                             </div>
                                        <input type="text" class="form-control" id="number" name="name" placeholder="Name" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                             </div>
                                        <input type="email" class="form-control" id="mail" name="email" placeholder="your email" required>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                        </div>
                                        <textarea name="message" class="form-control" placeholder="Your message" required></textarea>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <input type="submit" value="Submit" class="btn btn-info btn-block rounded-0 py-2">
                                </div>
                            </div>

                        </div>
                    </form>
                    <!--Form with header-->


                </div>
	</div>
</div>
{% endblock blog_card_block %}

blog_app/templates/blog_app/footer.html
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.1/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

blog_app/templates/blog_app/header.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

blog_app/templates/blog_app/home.html
{% extends 'blog_app/blog_structure.html' %}

{% block header_block %}
    {% include 'blog_app/header.html' %}
{% endblock header_block %}


{% block blog_card_block %}
    {% for post in posts %}
        {% include 'blog_app/blog_card.html' with post=post %}
    {% endfor %}
{% endblock blog_card_block %}

blog_app/templates/blog_app/login.html
{% extends 'blog_app/blog_structure.html' %}
{% block blog_card_block %}
<form class="col-sm-4 offset-sm-4" method="post" action="{% url 'blog_app:login_user' %}">
    <h2>Login Form</h2>
    <p class="text-danger">{{msg}}</p>
    {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
   
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock blog_card_block %}

blog_app/templates/blog_app/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Our Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" method="get" action="/search">
        <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% if user.is_authenticated %}
        <button type="button" class="btn btn-sm btn-danger"><a class="btn-outline-secondary text-decoration-none" href="{% url 'blog_app:logout_user' %}">Logout</a></button>
      {% else %}
      <button type="button" class="btn btn-sm btn-success"><a class="btn-outline-secondary text-decoration-none" href="{% url 'blog_app:login_user' %}">Login</a></button>
      
      {% endif %}
    </div>
  </div>
</nav>

blog_app/templates/blog_app/register.html
{% extends 'blog_app/blog_structure.html' %}
{% block blog_card_block %}
<form class="col-sm-4 offset-sm-4" method="post" action="{% url 'blog_app:register' %}">
    <h2>Registration Form</h2>
    <p class="text-danger">{{msg}}</p>
    {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
  </div>
   <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input name="email" type="email" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp" placeholder="Enter Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
   
  </div>
  <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock blog_card_block %}

blog_app/templates/blog_app/search.html
{% extends 'blog_app/blog_structure.html' %}
{% block blog_card_block %}
    {% for post in posts %}
        {% include 'blog_app/blog_card.html' with post=post %}
    {% endfor %}
{% endblock blog_card_block %}

blog_app/templates/blog_app/single_comment.html
<div class="comment mt-4 text-justify float-left" style="float:none"> <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
    <h4><a href="{% url 'blog_app:author_post' comment.author.id %}" style="text-decoration:none; color:white;">{{comment.author}}</a></h4> <br>
    <p>{{comment.body}}</p>
</div>

blog_app/templates/blog_app/single_post.html
{% extends 'blog_app/blog_structure.html' %}

{% block custom_head_block %}
<style>

    @media(min-width:568px) {
        .end {
            margin-left: auto
        }
    }

    @media(max-width:768px) {
        #post {
            width: 100%
        }
    }

    #clicked {
        padding-top: 1px;
        padding-bottom: 1px;
        text-align: center;
        width: 100%;
        background-color: #ecb21f;
        border-color: #a88734 #9c7e31 #846a29;
        color: black;
        border-width: 1px;
        border-style: solid;
        border-radius: 13px
    }

    #profile {
        background-color: unset
    }

    #post {
        margin: 10px;
        padding: 6px;
        padding-top: 2px;
        padding-bottom: 2px;
        text-align: center;
        background-color: #ecb21f;
        border-color: #a88734 #9c7e31 #846a29;
        color: black;
        border-width: 1px;
        border-style: solid;
        border-radius: 13px;
        width: 50%
    }

    #profile {
        text-decoration: none;
        color: rgb(224, 219, 219);
        background-color: black
    }

    .comments {
        margin-top: 5%;
        margin-left: 20px
    }

    .darker {
        border: 1px solid #ecb21f;
        background-color: black;
        float: right;
        border-radius: 5px;
        padding-left: 40px;
        padding-right: 30px;
        padding-top: 10px
    }

    .comment {
        border: 1px solid rgba(16, 46, 46, 1);
        background-color: rgba(16, 46, 46, 0.973);
        float: left;
        border-radius: 5px;
        padding-left: 40px;
        padding-right: 30px;
        padding-top: 10px
    }

    .comment h4,
    .comment span,
    .darker h4,
    .darker span {
        display: inline
    }

    .comment p,
    .comment span,
    .darker p,
    .darker span {
        color: rgb(184, 183, 183)
    }


    h4 {
        color: white;
        font-weight: bold
    }

    label {
        color: rgb(212, 208, 208)
    }

    #align-form {
        margin-top: 20px
    }

    .form-group p a {
        color: white
    }

    #checkbx {
        background-color: black
    }

    #darker img {
        margin-right: 15px;
        position: static
    }


</style>

{% endblock custom_head_block %}


{% block header_block %}
    <h1 class="text-center">{{post.title}}</h1>
{% endblock header_block %}


{% block single_post_block %}
    <img src="{{post.thumbnail.url}}" class="img rounded mx-auto d-block my-5" />
    <div class="my-3 mx-auto">
       {{post.body|safe}}
    </div>
{% endblock single_post_block %}


{% block single_post_comments %}

<section class="my-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 col-md-6 col-12 pb-4">
                <h1>Comments</h1>
                {% for comment in comments %}
                    {% include 'blog_app/single_comment.html' with comment=comment %}
                {% endfor %}
                {% comment %} <div class="comment mt-4 text-justify float-left"> <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                    <h4>Jhon Doe</h4>  <br>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>
                </div>
                <div class="comment mt-4 text-justify float-left"> <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
                    <h4>Rob Simpson</h4> <span>- 20 October, 2018</span> <br>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>
                </div>
                <div class="comment mt-4 text-justify"> <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                    <h4>Jhon Doe</h4> <span>- 20 October, 2018</span> <br>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>
                </div>
                <div class="comment mt-4 text-justify float-left"> <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
                    <h4>Rob Simpson</h4> <span>- 20 October, 2018</span> <br>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>
                </div> {% endcomment %}
            </div>
            <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
            {% if user.is_authenticated %}
                <form id="algin-form" method="post" action="{% url 'blog_app:add_comment' post.id %}">
                    {% csrf_token %}
                        <div class="form-group">
                            <h5>Leave a comment</h5> <label for="message">Message</label> <textarea name="msg" id="" msg cols="30" rows="5" class="form-control" style="background-color: black; color:white;"></textarea>
                        </div>
                        <div class="form-group"> <button type="submit" id="post" class="btn">Post Comment</button> </div>
                </form>
            {% else %}
                <h5>Login to post comments</h5>
            {% endif %}
                

            </div>
        </div>
    </div>
</section>
{% endblock single_post_comments %}